<template>
    <div>
        <p>Tabs 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
        <p>Switch 的文档</p>
    </div>
</template>